version = 2

[module]
type = "android-app"
name = "app"
languageLevel = "JAVA_8"
output = "build/classes"

[sourceSets.debug]
scope = "IMPLEMENTATION"
assets = ["src/debug/assets"]
java = ["src/debug/java", "src/debug/kotlin"]
jniLibs = ["src/debug/jniLibs"]
res = ["src/debug/res"]
resources = ["src/debug/resources"]

[sourceSets.main]
scope = "IMPLEMENTATION"
assets = ["src/main/assets"]
java = ["src/main/java", "src/main/kotlin"]
jniLibs = ["src/main/jniLibs"]
res = ["src/main/res"]
resources = ["src/main/resources"]

[sourceSets.release]
scope = "IMPLEMENTATION"
assets = ["src/release/assets"]
java = ["src/release/java", "src/release/kotlin"]
jniLibs = ["src/release/jniLibs"]
res = ["src/release/res"]
resources = ["src/release/resources"]

[dependencies]
implementation = ["com.google.android.material:material:1.14.0", "androidx.appcompat:appcompat:1.7.0", "androidx.core:core:1.13.1", "androidx.recyclerview:recyclerview:1.3.2", "androidx.viewpager2:viewpager2:1.1.0", "org.smali:baksmali:2.5.2", "org.smali:dexlib2:2.5.2", "org.smali:smali:2.5.2", "com.android.tools.build:apksig:8.5.0"]

[android]
namespace = "com.example.injector"
compileSdk = 34
minSdk = 24
targetSdk = 34
manifest = "src/main/AndroidManifest.xml"
versionCode = 1
versionName = "1.0"
isApplication = true
buildTypes = [{ name = "debug", debuggable = true, minifyEnabled = false, shrinkResources = false }, { name = "release", debuggable = false, minifyEnabled = false, shrinkResources = false, proguardFiles = ["proguard-android-optimize.txt", "proguard-rules.pro"] }]
